'use client';

import { normalizeCssControlInput } from '@/lib/html-editor/visual-style-adapter';

import { useState, useEffect, memo } from 'react';
import { Label } from './ui/label';
import Icon from './ui/icon';
import { useHtmlCssDesignSync as useDesignSync } from './use-html-css-design-sync';
import { useControlledInputs } from '@/hooks/use-controlled-input';
import { useModeToggle } from '@/hooks/use-mode-toggle';
import { useEditorStore } from '@/stores/useEditorStore';
import { extractMeasurementValue } from '@/lib/measurement-utils';

import type { Layer } from '@/types';
import { GapValueControl } from '@/app/(builder)/kodety/components/GapValueControl';
import { GridValueControl } from '@/app/(builder)/kodety/components/GridValueControl';
import {
  VisualSegmentedField,
  VisualSelectField,
  type VisualStyleOption,
} from '@/app/(builder)/kodety/components/VisualStyleField';

interface LayoutControlsProps {
  layer: Layer | null;
  onLayerUpdate: (layerId: string, updates: Partial<Layer>) => void;
  freeLayout?: boolean;
  onFreeLayoutChange?: (enabled: boolean) => void;
  visibleDisplay?: string;
  onVisibilityChange?: (visible: boolean) => void;
}

const LAYOUT_TYPE_OPTIONS: VisualStyleOption[] = [
  { value: 'columns', label: 'Columns', icon: <Icon name="columns" className="size-[12.5px]" /> },
  { value: 'rows', label: 'Rows', icon: <Icon name="rows" className="size-[12.5px]" /> },
  { value: 'grid', label: 'Grid', icon: <Icon name="grid" className="size-[12.5px]" /> },
];
const ALIGN_OPTIONS: VisualStyleOption[] = [
  { value: 'start', label: 'Start', icon: <Icon name="alignStart" className="size-[12.5px]" /> },
  { value: 'center', label: 'Center', icon: <Icon name="alignCenter" className="size-[12.5px]" /> },
  { value: 'end', label: 'End', icon: <Icon name="alignEnd" className="size-[12.5px]" /> },
  { value: 'stretch', label: 'Stretch', icon: <Icon name="alignStretch" className="size-[12.5px]" /> },
];
const JUSTIFY_OPTIONS: VisualStyleOption[] = [
  { value: 'start', label: 'Start' },
  { value: 'center', label: 'Center' },
  { value: 'end', label: 'End' },
  { value: 'between', label: 'Between' },
  { value: 'around', label: 'Around' },
  { value: 'evenly', label: 'Evenly' },
];
const WRAP_OPTIONS: VisualStyleOption[] = [
  { value: 'yes', label: 'Yes' },
  { value: 'no', label: 'No' },
];
const VISIBILITY_OPTIONS: VisualStyleOption[] = [
  { value: 'yes', label: 'Yes' },
  { value: 'no', label: 'No' },
];

const LayoutControls = memo(function LayoutControls({
  layer,
  onLayerUpdate,
  freeLayout = false,
  onFreeLayoutChange,
  visibleDisplay,
  onVisibilityChange,
}: LayoutControlsProps) {
  const activeBreakpoint = useEditorStore((s) => s.activeBreakpoint);
  const activeUIState = useEditorStore((s) => s.activeUIState);
  const {
    updateDesignProperty,
    updateDesignProperties,
    debouncedUpdateDesignProperty,
    cancelPendingDesignProperties,
    getDesignProperty,
  } = useDesignSync({
    layer,
    onLayerUpdate,
    activeBreakpoint,
    activeUIState,
  });

  // Get current values from layer (with inheritance)
  const display = getDesignProperty('layout', 'display') || '';
  const flexDirection = getDesignProperty('layout', 'flexDirection') || 'row';
  const alignItems = getDesignProperty('layout', 'alignItems') || '';
  const justifyContent = getDesignProperty('layout', 'justifyContent') || 'start';
  const flexWrap = getDesignProperty('layout', 'flexWrap') || 'nowrap';
  const gap = getDesignProperty('layout', 'gap') || '';
  const columnGap = getDesignProperty('layout', 'columnGap') || '';
  const rowGap = getDesignProperty('layout', 'rowGap') || '';
  const gridCols = getDesignProperty('layout', 'gridTemplateColumns') || '';
  const gridRows = getDesignProperty('layout', 'gridTemplateRows') || '';

  // Extract number from grid template: "repeat(2, 1fr)" → "2"
  const extractGridNumber = (value: string): string => {
    if (!value) return '';
    // Match the compact track formats generated by the visual control.
    const match = value.match(/^repeat\(\s*(\d+)\s*,\s*(?:1fr|minmax\(\s*0\s*,\s*1fr\s*\))\s*\)$/);
    return match ? match[1] : '';
  };

  // Convert number to grid template: "2" → "repeat(2, 1fr)"
  const numberToGridTemplate = (value: string): string | null => {
    const trimmed = value.trim();
    if (!trimmed) return null;
    // Only accept numbers
    if (!/^\d+$/.test(trimmed)) return null;
    return `repeat(${trimmed}, 1fr)`;
  };

  // Local state for grid inputs (number only)
  const [gridColsInput, setGridColsInput] = useState(extractGridNumber(gridCols));
  const [gridRowsInput, setGridRowsInput] = useState(extractGridNumber(gridRows));

  // Sync local state when layer values change
  useEffect(() => {
    setGridColsInput(extractGridNumber(gridCols));
  }, [gridCols]);

  useEffect(() => {
    setGridRowsInput(extractGridNumber(gridRows));
  }, [gridRows]);

  // Local controlled inputs (prevents repopulation bug)
  const inputs = useControlledInputs({
    gap,
    columnGap,
    rowGap,
  }, extractMeasurementValue);

  const [gapInput, setGapInput] = inputs.gap;
  const [columnGapInput, setColumnGapInput] = inputs.columnGap;
  const [rowGapInput, setRowGapInput] = inputs.rowGap;

  const gapInputValues: Record<string, string> = {
    gap: gapInput,
    columnGap: columnGapInput,
    rowGap: rowGapInput,
  };
  const gapProperties = ['gap', 'columnGap', 'rowGap'] as const;

  // Use mode toggle hook for gap
  const gapModeToggle = useModeToggle({
    category: 'layout',
    unifiedProperty: 'gap',
    individualProperties: ['columnGap', 'rowGap'],
    modeProperty: 'gapMode', // Store the mode preference in layer JSON
    updateDesignProperty,
    updateDesignProperties,
    getCurrentValue: (prop: string) => (
      gapInputValues[prop] ?? getDesignProperty('layout', prop) ?? ''
    ),
    getStoredMode: () => (layer?.design?.layout as Record<string, unknown>)?.gapMode as 'all' | 'individual' | null,
    scopeKey: layer?.id,
  });
  const handleGapModeToggle = () => {
    cancelPendingDesignProperties(gapProperties, 'layout');
    gapModeToggle.handleToggle();
  };

  // Determine layout type from current values
  const layoutDisplay = display === 'hidden' ? visibleDisplay || '' : display;
  const layoutType =
        layoutDisplay === 'grid' || layoutDisplay === 'inline-grid' ? 'grid' :
          flexDirection === 'column' || flexDirection === 'column-reverse' ? 'rows' :
            'columns';

  const wrapMode = flexWrap === 'wrap' ? 'yes' : 'no';
  const visibilityMode = display === 'hidden' ? 'no' : 'yes';

  // Handle layout type change
  const handleLayoutTypeChange = (type: 'columns' | 'rows' | 'grid') => {
    const updates = [];

    if (type === 'grid') {
      updates.push(
        { category: 'layout' as const, property: 'display', value: 'grid' },
        { category: 'layout' as const, property: 'flexDirection', value: null }
      );

      if (!gridCols || gridCols === 'none') {
        setGridColsInput('2');
        updates.push({
          category: 'layout' as const,
          property: 'gridTemplateColumns',
          value: numberToGridTemplate('2'),
        });
      }

      if (!gridRows || gridRows === 'none') {
        setGridRowsInput('1');
        updates.push({
          category: 'layout' as const,
          property: 'gridTemplateRows',
          value: numberToGridTemplate('1'),
        });
      }
    } else {
      updates.push(
        { category: 'layout' as const, property: 'display', value: 'flex' }
      );

      if (type === 'columns') {
        updates.push({ category: 'layout' as const, property: 'flexDirection', value: 'row' });
      } else {
        updates.push({ category: 'layout' as const, property: 'flexDirection', value: 'column' });
      }
    }

    updateDesignProperties(updates);
  };

  // Handle align items change
  const handleAlignChange = (value: string) => {
    updateDesignProperty('layout', 'alignItems', value);
  };

  // Handle justify content change
  const handleJustifyChange = (value: string) => {
    updateDesignProperty('layout', 'justifyContent', value);
  };

  // Handle wrap mode change
  const handleWrapChange = (value: 'yes' | 'no') => {
    updateDesignProperty('layout', 'flexWrap', value === 'yes' ? 'wrap' : 'nowrap');
  };

  const handleVisibilityChange = (value: 'yes' | 'no') => {
    if (onVisibilityChange) onVisibilityChange(value === 'yes');
    else updateDesignProperty('layout', 'display', value === 'yes' ? visibleDisplay || 'block' : 'hidden');
  };

  // Handle gap changes (debounced for text input)
  const handleGapChange = (value: string) => {
    setGapInput(value);
    if (gapModeToggle.mode === 'all') {
      const sanitized = normalizeCssControlInput(value);
      debouncedUpdateDesignProperty('layout', 'gap', sanitized || null);
    }
  };

  const handleColumnGapChange = (value: string) => {
    setColumnGapInput(value);
    const sanitized = normalizeCssControlInput(value);
    debouncedUpdateDesignProperty('layout', 'columnGap', sanitized || null);
  };

  const handleRowGapChange = (value: string) => {
    setRowGapInput(value);
    const sanitized = normalizeCssControlInput(value);
    debouncedUpdateDesignProperty('layout', 'rowGap', sanitized || null);
  };

  // Handle grid columns change (number input only)
  const handleGridColsChange = (value: string) => {
    // Only allow numbers and empty string
    if (value !== '' && !/^\d+$/.test(value)) return;

    setGridColsInput(value);
    const converted = numberToGridTemplate(value);
    debouncedUpdateDesignProperty('layout', 'gridTemplateColumns', converted);
  };

  // Handle grid rows change (number input only)
  const handleGridRowsChange = (value: string) => {
    // Only allow numbers and empty string
    if (value !== '' && !/^\d+$/.test(value)) return;

    setGridRowsInput(value);
    const converted = numberToGridTemplate(value);
    debouncedUpdateDesignProperty('layout', 'gridTemplateRows', converted);
  };

  // Extract numeric value from design property
  return (
    <div className="py-5" data-design-token-section="layout" data-kodety-onboarding="design-style-layout">
      <header className="-mt-4 flex items-center justify-between py-4">
        <Label>Layout</Label>
        {onFreeLayoutChange && (
          <button
            type="button"
            onClick={() => onFreeLayoutChange(!freeLayout)}
            className="group flex size-7 items-center justify-center rounded-[8px] text-muted-foreground outline-none transition-colors hover:bg-white/[.055] hover:text-foreground focus-visible:text-[var(--kodety-accent-hover)]"
            title={freeLayout ? 'Ativar layout HTML' : 'Usar canvas livre'}
            aria-label={freeLayout ? 'Ativar layout HTML' : 'Usar canvas livre'}
            aria-pressed={freeLayout}
          >
            {freeLayout ? (
              <Icon name="plus" className="size-3.5" />
            ) : (
              <span aria-hidden="true" className="h-px w-3.5 rounded-full bg-current transition-transform group-hover:scale-x-110" />
            )}
          </button>
        )}
      </header>

      <div className="flex flex-col gap-2">
        <div role="group" aria-label="Visible" data-html-layout-visibility>
          <VisualSegmentedField
            label="Visible"
            value={visibilityMode}
            options={VISIBILITY_OPTIONS}
            onValueChange={value => handleVisibilityChange(value as 'yes' | 'no')}
            property="display"
          />
        </div>
        {!freeLayout && (
          <>
            <VisualSegmentedField
              label="Type"
              value={layoutType}
              options={LAYOUT_TYPE_OPTIONS}
              onValueChange={value => handleLayoutTypeChange(value as 'columns' | 'rows' | 'grid')}
              property="display"
            />
            <VisualSegmentedField
              label="Align"
              value={alignItems || 'start'}
              options={ALIGN_OPTIONS}
              onValueChange={handleAlignChange}
              property="align-items"
              glyphClassName={layoutType === 'rows' ? '-rotate-90' : undefined}
            />
            <VisualSelectField
              label="Justify"
              value={justifyContent}
              options={JUSTIFY_OPTIONS}
              onValueChange={handleJustifyChange}
              ariaLabel="Justify content"
              property="justify-content"
            />
            {layoutType === 'grid' && (
              <GridValueControl
                columns={gridColsInput}
                rows={gridRowsInput}
                onColumnsChange={handleGridColsChange}
                onRowsChange={handleGridRowsChange}
              />
            )}
            {layoutType === 'columns' && (
              <VisualSegmentedField
                label="Wrap"
                value={wrapMode}
                options={WRAP_OPTIONS}
                onValueChange={value => handleWrapChange(value as 'yes' | 'no')}
                property="flex-wrap"
              />
            )}
            <GapValueControl
              mode={gapModeToggle.mode}
              value={gapInput}
              columnGap={columnGapInput}
              rowGap={rowGapInput}
              onValueChange={handleGapChange}
              onColumnGapChange={handleColumnGapChange}
              onRowGapChange={handleRowGapChange}
              onModeToggle={handleGapModeToggle}
            />
          </>
        )}
      </div>
    </div>
  );
});
export default LayoutControls;
