import type { HtmlProject, HtmlProjectFile } from './types';
import { readEditorMetadata } from './project-metadata';

export class WorkspaceProjectIdentityConflictError extends Error {
  readonly retryable = false;
  readonly preserveLocalDraft = true;

  constructor() {
    super('Outro projeto está ativo no WordPress. A edição local foi preservada; baixe uma cópia antes de abrir o projeto remoto.');
    this.name = 'WorkspaceProjectIdentityConflictError';
  }
}

/** A conflict is a rejected write, never permission to choose either author. */
export class WorkspaceContentConflictError extends Error {
  readonly retryable = false;
  readonly preserveLocalDraft = true;

  constructor(
    readonly conflictingPaths: string[],
    readonly base: HtmlProject,
    readonly local: HtmlProject,
    readonly remote: HtmlProject,
  ) {
    super(`Outra sessão alterou o mesmo conteúdo (${conflictingPaths.join(', ')}). O salvamento foi interrompido; suas alterações continuam nesta tela e as da outra sessão permanecem no servidor.`);
    this.name = 'WorkspaceContentConflictError';
  }
}

export interface WorkspaceMergeResult {
  project: HtmlProject;
  /** Files whose concurrent edits could not be composed without choosing an order. */
  recoveredPaths: string[];
}

const MISSING_JSON_VALUE = Symbol('missing JSON value');

function jsonObject(value: unknown): value is Record<string, unknown> {
  return Boolean(value && typeof value === 'object' && !Array.isArray(value));
}

function jsonEqual(left: unknown, right: unknown): boolean {
  if (Object.is(left, right)) return true;
  if (Array.isArray(left) && Array.isArray(right)) {
    return left.length === right.length && left.every((value, index) => jsonEqual(value, right[index]));
  }
  if (!jsonObject(left) || !jsonObject(right)) return false;
  const keys = Object.keys(left);
  return keys.length === Object.keys(right).length
    && keys.every(key => Object.hasOwn(right, key) && jsonEqual(left[key], right[key]));
}

/** Arrays are atomic: index-based reconciliation can remove or misassign rows. */
function mergeJsonValue(base: unknown, local: unknown, remote: unknown, path: string, conflicts: string[]): unknown {
  if (jsonEqual(local, remote)) return local;
  if (jsonEqual(local, base)) return remote;
  if (jsonEqual(remote, base)) return local;
  // This timestamp is generated by projectTransportMetadata on every upload;
  // it carries no authored content and the next upload generates it again.
  if (path === '.incode/project.json/updatedAt') return remote;
  if (jsonObject(base) && jsonObject(local) && jsonObject(remote)) {
    const entries: [string, unknown][] = [];
    for (const key of new Set([...Object.keys(base), ...Object.keys(local), ...Object.keys(remote)])) {
      const value = mergeJsonValue(
        Object.hasOwn(base, key) ? base[key] : MISSING_JSON_VALUE,
        Object.hasOwn(local, key) ? local[key] : MISSING_JSON_VALUE,
        Object.hasOwn(remote, key) ? remote[key] : MISSING_JSON_VALUE,
        `${path}/${key.replaceAll('~', '~0').replaceAll('/', '~1')}`,
        conflicts,
      );
      if (value !== MISSING_JSON_VALUE) entries.push([key, value]);
    }
    return Object.fromEntries(entries);
  }
  conflicts.push(path);
  return local;
}

function bytesEqual(left?: Uint8Array, right?: Uint8Array) {
  if (left === right) return true;
  if (!left || !right || left.byteLength !== right.byteLength) return false;
  for (let index = 0; index < left.byteLength; index++) {
    if (left[index] !== right[index]) return false;
  }
  return true;
}

function fileEqual(left?: HtmlProjectFile, right?: HtmlProjectFile) {
  if (left === right) return true;
  if (!left || !right) return false;
  return left.mimeType === right.mimeType
    && left.text === right.text
    && bytesEqual(left.data, right.data);
}

interface TextEdit {
  start: number;
  end: number;
  replacement: string;
  removed: string;
}

/** Return the smallest contiguous replacement that transforms base into next. */
function textEdit(base: string, next: string): TextEdit {
  let start = 0;
  const prefixLimit = Math.min(base.length, next.length);
  while (start < prefixLimit && base.charCodeAt(start) === next.charCodeAt(start)) start++;

  let baseEnd = base.length;
  let nextEnd = next.length;
  while (
    baseEnd > start
    && nextEnd > start
    && base.charCodeAt(baseEnd - 1) === next.charCodeAt(nextEnd - 1)
  ) {
    baseEnd--;
    nextEnd--;
  }
  return {
    start,
    end: baseEnd,
    replacement: next.slice(start, nextEnd),
    removed: base.slice(start, baseEnd),
  };
}

function applyEdit(source: string, edit: TextEdit) {
  return source.slice(0, edit.start) + edit.replacement + source.slice(edit.end);
}

function htmlRegionEnds(source: string) {
  const ends: number[] = [];
  let cursor = 0;
  while (cursor < source.length) {
    if (source[cursor] !== '<') {
      const next = source.indexOf('<', cursor);
      cursor = next < 0 ? source.length : next;
      ends.push(cursor);
      continue;
    }
    const start = cursor;
    if (source.startsWith('<!--', cursor)) {
      const end = source.indexOf('-->', cursor + 4);
      cursor = end < 0 ? source.length : end + 3;
    } else {
      let quote = '';
      cursor++;
      while (cursor < source.length) {
        const character = source[cursor++];
        if (quote) {
          if (character === quote) quote = '';
        } else if (character === '"' || character === "'") quote = character;
        else if (character === '>') break;
      }
    }
    ends.push(cursor);
    const rawTag = source.slice(start, cursor).match(/^<(script|style|textarea|title)\b/i)?.[1];
    if (rawTag) {
      const closing = source.toLowerCase().indexOf(`</${rawTag.toLowerCase()}`, cursor);
      cursor = closing < 0 ? source.length : closing;
      ends.push(cursor);
    }
  }
  return ends;
}

function cssRegionEnds(source: string) {
  const ends: number[] = [];
  let quote = '';
  let nesting = 0;
  for (let index = 0; index < source.length; index++) {
    const character = source[index];
    if (quote) {
      if (character === '\\') index++;
      else if (character === quote) quote = '';
    } else if (character === '"' || character === "'") quote = character;
    else if (source.startsWith('/*', index)) {
      const end = source.indexOf('*/', index + 2);
      index = end < 0 ? source.length : end + 1;
    } else if (character === '(' || character === '[') nesting++;
    else if (character === ')' || character === ']') nesting = Math.max(0, nesting - 1);
    else if (!nesting && (character === ';' || character === '{' || character === '}')) ends.push(index + 1);
  }
  ends.push(source.length);
  return ends;
}

function independentTextRegions(path: string, source: string, left: TextEdit, right: TextEdit) {
  const ends = /\.html?$/i.test(path) ? htmlRegionEnds(source) : /\.css$/i.test(path) ? cssRegionEnds(source) : [];
  if (!ends.length) return false;
  const region = (offset: number) => {
    const index = ends.findIndex(end => offset < end);
    return index < 0 ? ends.length - 1 : index;
  };
  const leftFirst = region(left.start);
  const leftLast = region(Math.max(left.start, left.end - 1));
  const rightFirst = region(right.start);
  const rightLast = region(Math.max(right.start, right.end - 1));
  return leftLast < rightFirst || rightLast < leftFirst;
}

function mergeText(base: string, local: string, remote: string): { text: string; recovered: boolean } {
  if (local === remote) return { text: local, recovered: false };
  if (local === base) return { text: remote, recovered: false };
  if (remote === base) return { text: local, recovered: false };

  const localEdit = textEdit(base, local);
  const remoteEdit = textEdit(base, remote);

  // Most visual Builder commands replace one attribute, text node or CSS
  // declaration. Compose two commands when their base ranges do not overlap.
  if (localEdit.end <= remoteEdit.start || remoteEdit.end <= localEdit.start) {
    const ordered = [localEdit, remoteEdit].sort((left, right) => right.start - left.start);
    return { text: ordered.reduce(applyEdit, base), recovered: false };
  }

  // A broader remote change may still leave the exact local target intact.
  // Replaying against that unique target preserves remote edits around it.
  if (localEdit.removed) {
    const first = remote.indexOf(localEdit.removed);
    if (first >= 0 && remote.indexOf(localEdit.removed, first + 1) < 0) {
      return {
        text: remote.slice(0, first) + localEdit.replacement + remote.slice(first + localEdit.removed.length),
        recovered: false,
      };
    }
  }

  // For competing insertions at the same stable cursor, retain both values in
  // server-then-local order. Other overlaps keep the local canvas canonical
  // and are accompanied by a private recovery copy of the remote file.
  if (
    localEdit.start === localEdit.end
    && remoteEdit.start === remoteEdit.end
    && localEdit.start === remoteEdit.start
  ) {
    return {
      text: base.slice(0, localEdit.start)
        + remoteEdit.replacement
        + localEdit.replacement
        + base.slice(localEdit.start),
      recovered: false,
    };
  }
  return { text: local, recovered: true };
}

function recoveryPath(path: string, occupied: Set<string>) {
  const safe = path.replace(/[^a-zA-Z0-9._-]+/g, '-').replace(/^-+|-+$/g, '') || 'arquivo';
  let candidate = `.incode/collaboration-recovery/${safe}.remote`;
  let suffix = 2;
  while (occupied.has(candidate)) candidate = `.incode/collaboration-recovery/${safe}-${suffix++}.remote`;
  occupied.add(candidate);
  return candidate;
}

function recoveryFile(path: string, source: HtmlProjectFile): HtmlProjectFile {
  return source.text !== undefined
    ? { path, mimeType: 'text/plain', text: source.text }
    : { path, mimeType: source.mimeType, data: source.data ? new Uint8Array(source.data) : new Uint8Array() };
}

/**
 * Three-way merge of a WordPress workspace.
 *
 * `base` is the last server-acknowledged snapshot, `local` is the live canvas,
 * and `remote` is the newer atomic workspace. Remote-only and local-only edits
 * are retained. Unresolvable same-range changes keep the user's live result and
 * preserve the remote bytes under `.incode/collaboration-recovery/`.
 */
export function mergeWorkspaceConflict(
  base: HtmlProject,
  local: HtmlProject,
  remote: HtmlProject,
): WorkspaceMergeResult {
  const identities = [base, local, remote].map(project =>
    String(readEditorMetadata(project).projectId || '').trim().toLowerCase(),
  );
  // A replacement is a different document, even when its paths are identical.
  // Legacy documents without identities can still merge with one another, but
  // an unknown identity must never inherit the identity of a known project.
  if (identities.some(identity => identity !== identities[0])) {
    throw new WorkspaceProjectIdentityConflictError();
  }
  const files: Record<string, HtmlProjectFile> = {};
  const occupied = new Set([...Object.keys(base.files), ...Object.keys(local.files), ...Object.keys(remote.files)]);
  const recoveredPaths: string[] = [];
  const paths = new Set(occupied);

  paths.forEach((path) => {
    const baseFile = base.files[path];
    const localFile = local.files[path];
    const remoteFile = remote.files[path];

    if (fileEqual(localFile, remoteFile)) {
      if (localFile) files[path] = localFile;
      return;
    }
    if (fileEqual(localFile, baseFile)) {
      if (remoteFile) files[path] = remoteFile;
      return;
    }
    if (fileEqual(remoteFile, baseFile)) {
      if (localFile) files[path] = localFile;
      return;
    }

    if (
      baseFile?.text !== undefined
      && localFile?.text !== undefined
      && remoteFile?.text !== undefined
      && localFile.mimeType === remoteFile.mimeType
    ) {
      const merged = mergeText(baseFile.text, localFile.text, remoteFile.text);
      files[path] = { ...localFile, path, text: merged.text };
      if (merged.recovered) {
        const recoveredPath = recoveryPath(path, occupied);
        files[recoveredPath] = recoveryFile(recoveredPath, remoteFile);
        recoveredPaths.push(recoveredPath);
      }
      return;
    }

    // Concurrent add/delete or binary replacement cannot be meaningfully
    // spliced. Keep the local intent and retain the server version privately.
    if (localFile) files[path] = localFile;
    if (remoteFile) {
      const recoveredPath = recoveryPath(path, occupied);
      files[recoveredPath] = recoveryFile(recoveredPath, remoteFile);
      recoveredPaths.push(recoveredPath);
    }
  });

  const localMainExists = Boolean(files[local.mainHtmlPath]);
  const remoteMainExists = Boolean(files[remote.mainHtmlPath]);
  return {
    project: {
      ...remote,
      ...local,
      files,
      mainHtmlPath: localMainExists
        ? local.mainHtmlPath
        : remoteMainExists
          ? remote.mainHtmlPath
          : Object.keys(files).find(path => /\.html?$/i.test(path)) || local.mainHtmlPath,
      openedAt: local.openedAt,
    },
    recoveredPaths,
  };
}

/**
 * Compose only independently authored changes. The caller must run this before
 * advancing its acknowledged snapshot/revision. A rejection leaves both drafts
 * intact and must not be retried against a newer revision without another merge.
 */
export function mergeWorkspaceConflictStrict(
  base: HtmlProject,
  local: HtmlProject,
  remote: HtmlProject,
): WorkspaceMergeResult {
  const identities = [base, local, remote].map(project =>
    String(readEditorMetadata(project).projectId || '').trim().toLowerCase(),
  );
  if (identities.some(identity => identity !== identities[0])) {
    throw new WorkspaceProjectIdentityConflictError();
  }
  const files: Record<string, HtmlProjectFile> = {};
  const conflicts: string[] = [];
  for (const path of new Set([...Object.keys(base.files), ...Object.keys(local.files), ...Object.keys(remote.files)])) {
    const baseFile = base.files[path];
    const localFile = local.files[path];
    const remoteFile = remote.files[path];
    if (fileEqual(localFile, remoteFile)) {
      if (localFile) files[path] = localFile;
    } else if (fileEqual(localFile, baseFile)) {
      if (remoteFile) files[path] = remoteFile;
    } else if (fileEqual(remoteFile, baseFile)) {
      if (localFile) files[path] = localFile;
    } else if (
      baseFile?.text !== undefined && localFile?.text !== undefined && remoteFile?.text !== undefined
      && baseFile.mimeType === localFile.mimeType && localFile.mimeType === remoteFile.mimeType
    ) {
      if (path.startsWith('.incode/') && path.endsWith('.json')) {
        try {
          const value = mergeJsonValue(
            JSON.parse(baseFile.text), JSON.parse(localFile.text), JSON.parse(remoteFile.text), path, conflicts,
          );
          files[path] = { ...localFile, text: JSON.stringify(value, null, 2) };
        } catch {
          // Invalid metadata must not fall back to character splicing.
          conflicts.push(path);
        }
      } else {
        const localEdit = textEdit(baseFile.text, localFile.text);
        const remoteEdit = textEdit(baseFile.text, remoteFile.text);
        const sameInsertion = localEdit.start === localEdit.end
          && remoteEdit.start === remoteEdit.end && localEdit.start === remoteEdit.start;
        if (!sameInsertion
          && (localEdit.end <= remoteEdit.start || remoteEdit.end <= localEdit.start)
          && independentTextRegions(path, baseFile.text, localEdit, remoteEdit)) {
          const ordered = [localEdit, remoteEdit].sort((left, right) => right.start - left.start);
          files[path] = { ...localFile, text: ordered.reduce(applyEdit, baseFile.text) };
        } else {
          conflicts.push(path);
        }
      }
    } else {
      // Includes delete-vs-edit, concurrent creation and binary replacements.
      conflicts.push(path);
    }
  }
  const name = mergeJsonValue(base.name, local.name, remote.name, 'project/name', conflicts) as string;
  const rootPath = mergeJsonValue(base.rootPath, local.rootPath, remote.rootPath, 'project/rootPath', conflicts) as string;
  const mainHtmlPath = mergeJsonValue(base.mainHtmlPath, local.mainHtmlPath, remote.mainHtmlPath, 'project/mainHtmlPath', conflicts) as string;
  if (conflicts.length) throw new WorkspaceContentConflictError(conflicts, base, local, remote);
  return { project: { ...remote, ...local, name, rootPath, mainHtmlPath, files }, recoveredPaths: [] };
}

/** Preserve normal sequential typing while rebasing writes queued before an ACK. */
export function rebaseQueuedWorkspaceProject(
  queuedBase: HtmlProject,
  requested: HtmlProject,
  acknowledged: HtmlProject,
  acknowledgedAuthoredProject?: HtmlProject,
): HtmlProject {
  if (queuedBase === acknowledged) return requested;
  return mergeWorkspaceConflictStrict(acknowledgedAuthoredProject || queuedBase, requested, acknowledged).project;
}
