import postcss, { type Rule } from 'postcss';
import { parse, parseFragment } from 'parse5';
import { prepareDuplicatedMarkup } from './source-patcher';

interface SourceLocation {
  startOffset: number;
  endOffset: number;
  startTag?: { startOffset: number; endOffset: number };
  attrs?: Record<string, { startOffset: number; endOffset: number }>;
}

interface ParsedNode {
  nodeName: string;
  tagName?: string;
  attrs?: Array<{ name: string; value: string }>;
  childNodes?: ParsedNode[];
  sourceCodeLocation?: SourceLocation;
}

export interface PreparedElementPaste {
  /** Markup with safe DOM identities and independent, per-copy CSS classes. */
  markup: string;
  /** Updated stylesheet text keyed by the same project path supplied by the caller. */
  stylesheets: Record<string, string>;
  changedStylesheetPaths: string[];
  /** Original class -> copy-specific class appended to the copied nodes. */
  classAliases: Record<string, string>;
  /** Original DOM id -> collision-free id generated by the structural duplicator. */
  idAliases: Record<string, string>;
}

const SIMPLE_CSS_IDENTIFIER = /^-?[A-Za-z_][\w-]*$/;
const NON_VISUAL_TAGS = new Set([
  'script', 'style', 'link', 'meta', 'base', 'title', 'noscript', 'template', 'br',
]);
let elementCopySequence = 0;

function elementChildren(node: ParsedNode) {
  return (node.childNodes || []).filter(child => Boolean(child.tagName));
}

function nodeTag(node: ParsedNode) {
  return node.tagName?.toLowerCase() || '';
}

function nodeAttribute(node: ParsedNode, name: string) {
  return node.attrs?.find(attribute => attribute.name.toLowerCase() === name.toLowerCase())?.value || '';
}

function walkElements(root: ParsedNode, visit: (node: ParsedNode, editorLayer: boolean) => void) {
  const walk = (node: ParsedNode, editorLayer: boolean) => {
    if (node.tagName) visit(node, editorLayer);
    const tag = nodeTag(node);
    elementChildren(node).forEach(child => walk(child, editorLayer && tag !== 'svg'));
  };
  elementChildren(root).forEach(node => walk(node, true));
}

function markupClassNames(source: string, fragment: boolean) {
  const root = (fragment
    ? parseFragment(source, { sourceCodeLocationInfo: false })
    : parse(source, { sourceCodeLocationInfo: false })) as ParsedNode;
  const names = new Set<string>();
  walkElements(root, node => {
    nodeAttribute(node, 'class').split(/\s+/).filter(Boolean).forEach(name => names.add(name));
  });
  return names;
}

function fragmentElements(source: string, sourceLocations: boolean) {
  const root = parseFragment(source, { sourceCodeLocationInfo: sourceLocations }) as ParsedNode;
  const nodes: ParsedNode[] = [];
  walkElements(root, node => nodes.push(node));
  return nodes;
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** Split a selector list without treating commas inside :is(), attributes or strings as separators. */
function splitSelectorList(selector: string) {
  const parts: string[] = [];
  let start = 0;
  let roundDepth = 0;
  let squareDepth = 0;
  let quote = '';
  let escaped = false;
  for (let index = 0; index < selector.length; index += 1) {
    const character = selector[index];
    if (escaped) {
      escaped = false;
      continue;
    }
    if (character === '\\') {
      escaped = true;
      continue;
    }
    if (quote) {
      if (character === quote) quote = '';
      continue;
    }
    if (character === '"' || character === "'") {
      quote = character;
      continue;
    }
    if (character === '(') roundDepth += 1;
    else if (character === ')') roundDepth = Math.max(0, roundDepth - 1);
    else if (character === '[') squareDepth += 1;
    else if (character === ']') squareDepth = Math.max(0, squareDepth - 1);
    else if (character === ',' && roundDepth === 0 && squareDepth === 0) {
      parts.push(selector.slice(start, index).trim());
      start = index + 1;
    }
  }
  parts.push(selector.slice(start).trim());
  return parts.filter(Boolean);
}

function selectorClassNames(source: string) {
  const names = new Set<string>();
  let root;
  try {
    root = postcss.parse(source);
  } catch {
    return names;
  }
  root.walkRules(rule => {
    for (const match of rule.selector.matchAll(/\.(-?[A-Za-z_][\w-]*)(?![\w-])/g)) {
      names.add(match[1]);
    }
  });
  return names;
}

function uniqueCopyClassName(sourceName: string, reserved: Set<string>) {
  const stem = `${sourceName}-copy`;
  let candidate = stem;
  let suffix = 2;
  while (reserved.has(candidate)) candidate = `${stem}-${suffix++}`;
  reserved.add(candidate);
  return candidate;
}

function copyNamespace() {
  return globalThis.crypto?.randomUUID?.().replace(/-/g, '').slice(0, 12)
    || `${Date.now().toString(36)}-${(++elementCopySequence).toString(36)}`;
}

function generatedLayerClass(node: ParsedNode, namespace: string, index: number) {
  const tag = nodeTag(node) || 'layer';
  const label = (nodeAttribute(node, 'data-label') || tag)
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 36) || tag;
  return `incode-${label}-copy-${namespace}-${index + 1}`;
}

/**
 * Keep the original class as a behavior/shared-style hook and append a unique
 * alias immediately after it. Cloned CSS qualifies the source selector with
 * that alias, so the pasted subtree wins with its own declarations while JS
 * that targets the original class keeps working.
 */
function appendCopyClasses(markup: string, classAliases: Record<string, string>) {
  const root = parseFragment(markup, { sourceCodeLocationInfo: true }) as ParsedNode;
  const nodes: Array<{ node: ParsedNode; editorLayer: boolean }> = [];
  walkElements(root, (node, editorLayer) => nodes.push({ node, editorLayer }));
  const namespace = copyNamespace();
  const reserved = markupClassNames(markup, true);
  Object.values(classAliases).forEach(name => reserved.add(name));
  const patches: Array<{ start: number; end: number; text: string }> = [];

  nodes.forEach(({ node, editorLayer }, index) => {
    const tag = nodeTag(node);
    if (!tag || NON_VISUAL_TAGS.has(tag) || !node.sourceCodeLocation?.startTag) return;
    const classes = nodeAttribute(node, 'class').split(/\s+/).filter(Boolean);
    const nextClasses: string[] = [];
    let hasCopyAlias = false;
    classes.forEach(className => {
      if (!nextClasses.includes(className)) nextClasses.push(className);
      const alias = classAliases[className];
      if (alias && !nextClasses.includes(alias)) {
        nextClasses.push(alias);
        hasCopyAlias = true;
      }
    });
    // A layer with no locally cloneable rule still needs a copy-specific class
    // so its next Inspector edit creates an independent selector.
    if (editorLayer && !hasCopyAlias) {
      let generated = generatedLayerClass(node, namespace, index);
      let suffix = 2;
      while (reserved.has(generated)) generated = `${generatedLayerClass(node, namespace, index)}-${suffix++}`;
      reserved.add(generated);
      nextClasses.push(generated);
    }

    const location = node.sourceCodeLocation;
    const existing = location.attrs?.class;
    if (existing) {
      patches.push({
        start: existing.startOffset,
        end: existing.endOffset,
        text: `class="${nextClasses.join(' ')}"`,
      });
      return;
    }
    if (!nextClasses.length) return;
    const startTag = location.startTag!;
    const nameLength = markup.slice(startTag.startOffset, startTag.endOffset).match(/^<[^\s/>]+/)?.[0].length || 0;
    const start = startTag.startOffset + nameLength;
    patches.push({ start, end: start, text: ` class="${nextClasses.join(' ')}"` });
  });

  const parts: string[] = [];
  let offset = 0;
  patches.sort((left, right) => left.start - right.start).forEach(patch => {
    parts.push(markup.slice(offset, patch.start), patch.text);
    offset = patch.end;
  });
  parts.push(markup.slice(offset));
  return parts.join('');
}

function duplicatedIdAliases(originalMarkup: string, duplicatedMarkup: string) {
  const originalNodes = fragmentElements(originalMarkup, false);
  const duplicatedNodes = fragmentElements(duplicatedMarkup, false);
  const aliases: Record<string, string> = {};
  originalNodes.forEach((node, index) => {
    const originalId = nodeAttribute(node, 'id');
    const duplicatedId = nodeAttribute(duplicatedNodes[index] || {}, 'id');
    if (
      originalId
      && duplicatedId
      && originalId !== duplicatedId
      && SIMPLE_CSS_IDENTIFIER.test(originalId)
      && SIMPLE_CSS_IDENTIFIER.test(duplicatedId)
    ) aliases[originalId] = duplicatedId;
  });
  return aliases;
}

function qualifyClassRuns(selector: string, sourceName: string, alias: string) {
  const token = `\\.${escapeRegExp(sourceName)}(?![\\w-])`;
  const run = new RegExp(`(?:${token})+`, 'g');
  const single = new RegExp(token, 'g');
  return selector.replace(run, match => {
    const count = match.match(single)?.length || 1;
    return `${match}${`.${alias}`.repeat(count)}`;
  });
}

/**
 * A copied node may have been styled through an ancestor that is not part of
 * the copied subtree (`.hero .button`). Keep the faithful contextual clone and
 * also detach the selector at the first copy identity (`.button.button-copy`).
 * Copy aliases are unique, so this fallback cannot leak onto the original.
 */
function selectorFromFirstCopyIdentity(
  selector: string,
  classAliases: Record<string, string>,
  idAliases: Record<string, string>,
) {
  const needles = [
    ...Object.values(classAliases).map(alias => `.${alias}`),
    ...Object.values(idAliases).map(alias => `#${alias}`),
  ];
  const identityIndex = needles.reduce((earliest, needle) => {
    const index = selector.indexOf(needle);
    return index < 0 ? earliest : Math.min(earliest, index);
  }, Number.POSITIVE_INFINITY);
  if (!Number.isFinite(identityIndex) || identityIndex <= 0) return selector;

  let start = 0;
  let roundDepth = 0;
  let squareDepth = 0;
  let quote = '';
  let escaped = false;
  for (let index = 0; index < identityIndex; index += 1) {
    const character = selector[index];
    if (escaped) {
      escaped = false;
      continue;
    }
    if (character === '\\') {
      escaped = true;
      continue;
    }
    if (quote) {
      if (character === quote) quote = '';
      continue;
    }
    if (character === '"' || character === "'") {
      quote = character;
      continue;
    }
    if (character === '(') roundDepth += 1;
    else if (character === ')') roundDepth = Math.max(0, roundDepth - 1);
    else if (character === '[') squareDepth += 1;
    else if (character === ']') squareDepth = Math.max(0, squareDepth - 1);
    else if (roundDepth === 0 && squareDepth === 0) {
      if (character === '>' || character === '+' || character === '~') {
        start = index + 1;
      } else if (/\s/.test(character)) {
        let next = index + 1;
        while (next < identityIndex && /\s/.test(selector[next])) next += 1;
        start = next;
        index = next - 1;
      }
    }
  }
  return selector.slice(start).trim() || selector;
}

function transformSelector(
  selector: string,
  classAliases: Record<string, string>,
  idAliases: Record<string, string>,
) {
  const transformed = splitSelectorList(selector).flatMap(part => {
    let next = part;
    Object.entries(classAliases).forEach(([sourceName, alias]) => {
      next = qualifyClassRuns(next, sourceName, alias);
    });
    Object.entries(idAliases).forEach(([sourceId, alias]) => {
      next = next.replace(
        new RegExp(`#${escapeRegExp(sourceId)}(?![\\w-])`, 'g'),
        `#${alias}`,
      );
    });
    if (next === part) return [];
    const independent = selectorFromFirstCopyIdentity(next, classAliases, idAliases);
    return independent === next ? [next] : [next, independent];
  });
  return Array.from(new Set(transformed)).join(', ');
}

/** Clone matching base, pseudo-state and nested media rules beside their originals. */
export function duplicateElementSelectorsInCss(
  source: string,
  classAliases: Record<string, string>,
  idAliases: Record<string, string> = {},
) {
  if (!Object.keys(classAliases).length && !Object.keys(idAliases).length) return source;
  let root;
  try {
    root = postcss.parse(source);
  } catch {
    return source;
  }
  const matches: Array<{ rule: Rule; selector: string }> = [];
  root.walkRules(rule => {
    const selector = transformSelector(rule.selector, classAliases, idAliases);
    if (selector) matches.push({ rule, selector });
  });
  matches.forEach(({ rule, selector }) => rule.after(rule.clone({ selector })));
  return root.toString();
}

/**
 * Build the full, typed element-paste payload. Structural identities, classes
 * and CSS are prepared together so HTML can never reference a copy class whose
 * declaration was omitted from the same transaction.
 */
export function prepareIndependentElementPaste(
  targetSource: string,
  copiedMarkup: string,
  stylesheets: Record<string, string>,
): PreparedElementPaste {
  const structurallySafeMarkup = prepareDuplicatedMarkup(targetSource, copiedMarkup);
  const idAliases = duplicatedIdAliases(copiedMarkup, structurallySafeMarkup);
  const stylesheetClassNames = new Set<string>();
  Object.values(stylesheets).forEach(source => {
    selectorClassNames(source).forEach(name => stylesheetClassNames.add(name));
  });
  const reserved = markupClassNames(targetSource, false);
  stylesheetClassNames.forEach(name => reserved.add(name));
  const classAliases: Record<string, string> = {};
  markupClassNames(structurallySafeMarkup, true).forEach(className => {
    if (!SIMPLE_CSS_IDENTIFIER.test(className) || !stylesheetClassNames.has(className)) return;
    classAliases[className] = uniqueCopyClassName(className, reserved);
  });

  const nextStylesheets: Record<string, string> = {};
  const changedStylesheetPaths: string[] = [];
  Object.entries(stylesheets).forEach(([path, source]) => {
    const next = duplicateElementSelectorsInCss(source, classAliases, idAliases);
    nextStylesheets[path] = next;
    if (next !== source) changedStylesheetPaths.push(path);
  });

  return {
    markup: appendCopyClasses(structurallySafeMarkup, classAliases),
    stylesheets: nextStylesheets,
    changedStylesheetPaths: changedStylesheetPaths.sort(),
    classAliases,
    idAliases,
  };
}
