import type { McpRuntimeActivity } from './editor-types';

export interface McpActivityPresentation {
  activeLabel: string;
  successLabel: string;
  errorLabel: string;
  description?: string;
  notify: boolean;
}

interface ActivityLabels {
  active: string;
  success: string;
  error: string;
}

const portugueseLabels: Record<string, ActivityLabels> = {
  publish: {
    active: 'MCP publicando o site',
    success: 'Site publicado pelo MCP',
    error: 'Falha ao publicar pelo MCP',
  },
  upsert_section: {
    active: 'MCP atualizando uma seção',
    success: 'Seção atualizada pelo MCP',
    error: 'O MCP não conseguiu atualizar a seção',
  },
  write_file: {
    active: 'MCP gravando no projeto',
    success: 'Arquivo atualizado pelo MCP',
    error: 'O MCP não conseguiu gravar o arquivo',
  },
  replace_in_file: {
    active: 'MCP aplicando uma alteração',
    success: 'Alteração aplicada pelo MCP',
    error: 'O MCP não conseguiu aplicar a alteração',
  },
  delete_file: {
    active: 'MCP removendo um arquivo',
    success: 'Arquivo removido pelo MCP',
    error: 'O MCP não conseguiu remover o arquivo',
  },
  update_settings: {
    active: 'MCP atualizando as configurações',
    success: 'Configurações atualizadas pelo MCP',
    error: 'O MCP não conseguiu atualizar as configurações',
  },
  upsert_content: {
    active: 'MCP salvando conteúdo',
    success: 'Conteúdo salvo pelo MCP',
    error: 'O MCP não conseguiu salvar o conteúdo',
  },
  delete_content: {
    active: 'MCP removendo conteúdo',
    success: 'Conteúdo removido pelo MCP',
    error: 'O MCP não conseguiu remover o conteúdo',
  },
  create_collection: {
    active: 'MCP criando uma collection',
    success: 'Collection criada pelo MCP',
    error: 'O MCP não conseguiu criar a collection',
  },
  update_collection_fields: {
    active: 'MCP atualizando uma collection',
    success: 'Collection atualizada pelo MCP',
    error: 'O MCP não conseguiu atualizar a collection',
  },
  upload_media: {
    active: 'MCP enviando uma mídia',
    success: 'Mídia enviada pelo MCP',
    error: 'O MCP não conseguiu enviar a mídia',
  },
  generate_ai_content: {
    active: 'MCP gerando conteúdo',
    success: 'Conteúdo gerado pelo MCP',
    error: 'O MCP não conseguiu gerar o conteúdo',
  },
};

const englishLabels: Record<string, ActivityLabels> = {
  publish: {
    active: 'MCP is publishing the site',
    success: 'Site published by MCP',
    error: 'MCP could not publish the site',
  },
  upsert_section: {
    active: 'MCP is updating a section',
    success: 'Section updated by MCP',
    error: 'MCP could not update the section',
  },
  write_file: {
    active: 'MCP is writing to the project',
    success: 'File updated by MCP',
    error: 'MCP could not update the file',
  },
  replace_in_file: {
    active: 'MCP is applying a change',
    success: 'Change applied by MCP',
    error: 'MCP could not apply the change',
  },
  delete_file: {
    active: 'MCP is removing a file',
    success: 'File removed by MCP',
    error: 'MCP could not remove the file',
  },
  update_settings: {
    active: 'MCP is updating settings',
    success: 'Settings updated by MCP',
    error: 'MCP could not update settings',
  },
  upsert_content: {
    active: 'MCP is saving content',
    success: 'Content saved by MCP',
    error: 'MCP could not save the content',
  },
  delete_content: {
    active: 'MCP is removing content',
    success: 'Content removed by MCP',
    error: 'MCP could not remove the content',
  },
  create_collection: {
    active: 'MCP is creating a collection',
    success: 'Collection created by MCP',
    error: 'MCP could not create the collection',
  },
  update_collection_fields: {
    active: 'MCP is updating a collection',
    success: 'Collection updated by MCP',
    error: 'MCP could not update the collection',
  },
  upload_media: {
    active: 'MCP is uploading media',
    success: 'Media uploaded by MCP',
    error: 'MCP could not upload the media',
  },
  generate_ai_content: {
    active: 'MCP is generating content',
    success: 'Content generated by MCP',
    error: 'MCP could not generate the content',
  },
};

function boundedText(value: unknown) {
  return typeof value === 'string' ? value.trim().slice(0, 180) : '';
}

function targetDescription(activity: McpRuntimeActivity, english: boolean) {
  const release = boundedText(activity.result?.release);
  if (release) return `Release ${release}`;
  const sectionId = boundedText(activity.target?.sectionId || activity.result?.sectionId);
  const page = boundedText(activity.target?.page || activity.result?.page);
  if (sectionId && page) {
    return english ? `Section “${sectionId}” · ${page}` : `Seção “${sectionId}” · ${page}`;
  }
  if (sectionId) return english ? `Section “${sectionId}”` : `Seção “${sectionId}”`;
  const path = boundedText(activity.target?.path);
  if (path) return path;
  return undefined;
}

export function mcpActivityToastId(activityId: string) {
  return `kodety-mcp-activity-${activityId}`;
}

export function mcpActivityPresentation(
  activity: McpRuntimeActivity | null | undefined,
  locale = 'pt-BR',
): McpActivityPresentation {
  const english = locale.toLowerCase().startsWith('en');
  const labels = english ? englishLabels : portugueseLabels;
  const tool = boundedText(activity?.tool);
  const reading = activity?.phase === 'reading';
  const fallback: ActivityLabels = reading
    ? english
      ? { active: 'MCP is reading the project', success: 'MCP finished reading', error: 'MCP could not read the project' }
      : { active: 'MCP lendo o projeto', success: 'Leitura do MCP concluída', error: 'O MCP não conseguiu ler o projeto' }
    : english
      ? { active: 'MCP is updating the project', success: 'Project updated by MCP', error: 'MCP could not update the project' }
      : { active: 'MCP atualizando o projeto', success: 'Projeto atualizado pelo MCP', error: 'O MCP não conseguiu atualizar o projeto' };
  const selected = labels[tool] || fallback;
  return {
    activeLabel: selected.active,
    successLabel: selected.success,
    errorLabel: selected.error,
    description: activity?.success === false
      ? boundedText(activity.message) || targetDescription(activity, english)
      : targetDescription(activity || {}, english),
    // Reads may be frequent and are already visible in the live HUD. Reserve
    // durable notifications for work that changes or generates something.
    notify: !reading,
  };
}
